set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER /opt/aarch64v8-marvell-linux-gnu-5.2.1_x86_64_20160301/bin/aarch64-linux-gnu-gcc)
set(CMAKE_C_FLAGS -static)

set(CMAKE_FIND_ROOT_PATH /opt/aarch64v8-marvell-linux-gnu-5.2.1_x86_64_20160301)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
